Repository github/cleanowners, pull requests merged in 2024-11, with the labels that each got.

#155 feat: support github enterprise api
  .env-example
  README.md
  auth.py
  cleanowners.py
  env.py
  test_auth.py
  test_env.py
Labels: feature, release

#159 chore: Simplify main function by extracting new functions and adding tests
  cleanowners.py
  test_cleanowners.py
Labels: maintenance, automation

#162 test: improve auth test coverage
  test_auth.py
Labels: automation

#166 chore: github actions cleanup
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yaml
  .github/workflows/super-linter.yaml
Labels: maintenance
