Repository github/cleanowners, pull requests merged in 2024-05, with the labels that each got.

#71 chore: add OSSF scorecard github action and README badge
  .github/workflows/auto-labeler.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yaml
  .github/workflows/super-linter.yaml
  Dockerfile
  README.md
Labels: maintenance

#72 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yaml
Labels: maintenance, release

#76 chore: Switch to weekly dep updates to reduce noise
  .github/dependabot.yml
Labels: maintenance

#80 chore: add pull_request_target for releases
  .github/workflows/release.yml
Labels: maintenance

#83 ci: release when a new feature hits main
  .github/workflows/release.yml
Labels: automation

#84 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
Labels: maintenance
