Repository github/cleanowners, pull requests merged in 2024-03, with the labels that each got.

#24 fix:pull request function
  cleanowners.py
  test_cleanowners.py
Labels: bug

#31 Create stale.yaml
  .github/workflows/stale.yaml
Labels: infrastructure

#30 feat: allow github app authentication
  .env-example
  .github/workflows/python-ci.yml
  README.md
  auth.py
  cleanowners.py
  env.py
  requirements-test.txt
  requirements.txt
  test_auth.py
  test_env.py
Labels: enhancement

#34 Use keep label to exempt issues as needed
  .github/workflows/stale.yaml
Labels: infrastructure

#32 fix: handle if ORGANIZATION not provided
  Makefile
  cleanowners.py
  requirements-test.txt
  test_auth.py
  test_cleanowners.py
Labels: bug

#38 chore: fix linting issues to allow upgrade to super-linterv6
  .github/linters/.flake8
  .github/linters/.python-lint
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/python-ci.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yaml
  .github/workflows/super-linter.yaml
  .pylintrc
  Dockerfile
  Makefile
  README.md
Labels: infrastructure
